

SKILLS = {
    'None': {
        'None': ['Loaf Around', 'Rest', 'Splash']
    },
    'Utility': {
        'None': ['', '', ''],
        'Utility': ['Barrier', 'Cripple', 'Driving Force'],
        'Healer': ['Restore', 'Boost', 'Driving Force'],
        'Vanguard': ['Stone Boots', 'Cripple', 'Driving Force'],
        'Warden': ['Stomp', 'Rally', 'Driving Force'],
        'Juggernaut': ['Barrier', 'Rally', 'Driving Force'],
        'Diver': ['Concussion', 'Cripple', 'Driving Force'],
        'Burst Mage': ['Concussion', 'Rally', 'Driving Force'],
        'Battle Mage': ['Barrier', 'Rally', 'Driving Force'],
        'Artillery Mage': ['Restore', 'Cripple', 'Driving Force'],
        'Control Mage': ['Concussion', 'Stomp', 'Driving Force'],
        'Assassin': ['Concussion', 'Cripple', 'Driving Force'],
        'Skirmisher': ['Concussion', 'Rally', 'Driving Force'],
        'Marksman': ['Stomp', 'Boost', 'Driving Force']
    },
    'Healer': {
        'None': ['', '', ''],
        'Utility': ['Restore', 'Stone Boots', 'Saving Grace'],
        'Healer': ['Restore', 'Boost', 'Saving Grace'],
        'Vanguard': ['Drain', 'Stone Boots', 'Saving Grace'],
        'Warden': ['Restore', 'Bulk Up', 'Saving Grace'],
        'Juggernaut': ['Barrier', 'Bulk Up', 'Saving Grace'],
        'Diver': ['Barrier', 'Boost', 'Saving Grace'],
        'Burst Mage': ['Drain', 'Boost', 'Saving Grace'],
        'Battle Mage': ['Drain', 'Boost', 'Saving Grace'],
        'Artillery Mage': ['Restore', 'Bulk Up', 'Saving Grace'],
        'Control Mage': ['Restore', 'Bulk Up', 'Saving Grace'],
        'Assassin': ['Drain', 'Stone Boots', 'Saving Grace'],
        'Skirmisher': ['Drain', 'Boost', 'Saving Grace'],
        'Marksman': ['Barrier', 'Bulk Up', 'Saving Grace']
    },
    'Vanguard': {
        'None': ['', '', ''],
        'Utility': ['Stone Boots', 'Hook', 'Ionic Explosion'],
        'Healer': ['Bulk Up', 'Enrage', 'Ionic Explosion'],
        'Vanguard': ['Concussion', 'Close In', 'Ionic Explosion'],
        'Warden': ['Bulk Up', 'Hook', 'Ionic Explosion'],
        'Juggernaut': ['Concussion', 'Hook', 'Ionic Explosion'],
        'Diver': ['Concussion', 'Close In', 'Ionic Explosion'],
        'Burst Mage': ['Concussion', 'Enrage', 'Ionic Explosion'],
        'Battle Mage': ['Bulk Up', 'Close In', 'Ionic Explosion'],
        'Artillery Mage': ['Stone Boots', 'Hook', 'Ionic Explosion'],
        'Control Mage': ['Stone Boots', 'Hook', 'Ionic Explosion'],
        'Assassin': ['Concussion', 'Close In', 'Ionic Explosion'],
        'Skirmisher': ['Concussion', 'Enrage', 'Ionic Explosion'],
        'Marksman': ['Bulk Up', 'Close In', 'Ionic Explosion']
    },
    'Warden': {
        'None': ['', '', ''],
        'Utility': ['Reinforce', 'Boost', 'Look At Me'],
        'Healer': ['Restore', 'Bulk Up', 'Look At Me'],
        'Vanguard': ['Stone Boots', 'Cripple', 'Look At Me'],
        'Warden': ['Reinforce', 'Bulk Up', 'Look At Me'],
        'Juggernaut': ['Reinforce', 'Bulk Up', 'Look At Me'],
        'Diver': ['Stone Boots', 'Cripple', 'Look At Me'],
        'Burst Mage': ['Restore', 'Boost', 'Look At Me'],
        'Battle Mage': ['Restore', 'Criple', 'Look At Me'],
        'Artillery Mage': ['Restore', 'Criple', 'Look At Me'],
        'Control Mage': ['Reinforce', 'Boost', 'Look At Me'],
        'Assassin': ['Stone Boots', 'Cripple', 'Look At Me'],
        'Skirmisher': ['Stone Boots', 'Boost', 'Look At Me'],
        'Marksman': ['Reinforce', 'Boost', 'Look At Me']
    },
    'Juggernaut': {
        'None': ['', '', ''],
        'Utility': ['Hook', 'Pierce', 'Power Within'],
        'Healer': ['Drain', 'Concussion', 'Power Within'],
        'Vanguard': ['Hook', 'Pierce', 'Power Within'],
        'Warden': ['Drain', 'Stomp', 'Power Within'],
        'Juggernaut': ['Chop', 'Stomp', 'Power Within'],
        'Diver': ['Drain', 'Concussion', 'Power Within'],
        'Burst Mage': ['Chop', 'Concussion', 'Power Within'],
        'Battle Mage': ['Chop', 'Stomp', 'Power Within'],
        'Artillery Mage': ['Hook', 'Pierce', 'Power Within'],
        'Control Mage': ['Hook', 'Concussion', 'Power Within'],
        'Assassin': ['Chop', 'Pierce', 'Power Within'],
        'Skirmisher': ['Chop', 'Pierce', 'Power Within'],
        'Marksman': ['Chop', 'Pierce', 'Power Within']
    },
    'Diver': {
        'None': ['', '', ''],
        'Utility': ['Concussion', 'Close In', 'Subdue'],
        'Healer': ['Concussion', 'Stomp', 'Subdue'],
        'Vanguard': ['Pin Down', 'Close In', 'Subdue'],
        'Warden': ['Stomp', 'Close In', 'Subdue'],
        'Juggernaut': ['Pin Down', 'Cripple', 'Subdue'],
        'Diver': ['Pin Down', 'Close In', 'Subdue'],
        'Burst Mage': ['Concussion', 'Cripple', 'Subdue'],
        'Battle Mage': ['Stomp', 'Energize', 'Subdue'],
        'Artillery Mage': ['Concussion', 'Cripple', 'Subdue'],
        'Control Mage': ['Stomp', 'Energize', 'Subdue'],
        'Assassin': ['Pin Down', 'Close In', 'Subdue'],
        'Skirmisher': ['Stomp', 'Energize', 'Subdue'],
        'Marksman': ['Stomp', 'Cripple', 'Subdue']
    },
    'Burst Mage': {
        'None': ['', '', ''],
        'Utility': ['Pin Down', 'Fireball', 'Magiblast'],
        'Healer': ['Drain', 'Fireball', 'Magiblast'],
        'Vanguard': ['Pin Down', 'Energize', 'Magiblast'],
        'Warden': ['Pin Down', 'Fireball', 'Magiblast'],
        'Juggernaut': ['Drain', 'Energize', 'Magiblast'],
        'Diver': ['Fireball', 'Close In', 'Magiblast'],
        'Burst Mage': ['Fireball', 'Energize', 'Magiblast'],
        'Battle Mage': ['Fireball', 'Energize', 'Magiblast'],
        'Artillery Mage': ['Fireball', 'Enrage', 'Magiblast'],
        'Control Mage': ['Energize', 'Enrage', 'Magiblast'],
        'Assassin': ['Close In', 'Fireball', 'Magiblast'],
        'Skirmisher': ['Enrage', 'Energize', 'Magiblast'],
        'Marksman': ['Fireball', 'Drain', 'Magiblast']
    },
    'Battle Mage': {
        'None': ['', '', ''],
        'Utility': ['Stomp', 'Energize', 'Storm Surge'],
        'Healer': ['Drain', 'Energize', 'Storm Surge'],
        'Vanguard': ['Pin Down', 'Energize', 'Storm Surge'],
        'Warden': ['Stomp', 'Energize', 'Storm Surge'],
        'Juggernaut': ['Stomp', 'Drain', 'Storm Surge'],
        'Diver': ['Close In', 'Drain', 'Storm Surge'],
        'Burst Mage': ['Energize', 'Fireball', 'Storm Surge'],
        'Battle Mage': ['Bulk Up', 'Energize', 'Storm Surge'],
        'Artillery Mage': ['Fireball', 'Energize', 'Storm Surge'],
        'Control Mage': ['Energize', 'Stomp', 'Storm Surge'],
        'Assassin': ['Close In', 'Energize', 'Storm Surge'],
        'Skirmisher': ['Pierce', 'Energize', 'Storm Surge'],
        'Marksman': ['Fireball', 'Stomp', 'Storm Surge']
    },
    'Artillery Mage': {
        'None': ['', '', ''],
        'Utility': ['Cripple', 'Barrage', 'Force Cannon'],
        'Healer': ['Drain', 'Barrage', 'Force Cannon'],
        'Vanguard': ['Stone Boots', 'Fireball', 'Force Cannon'],
        'Warden': ['Stomp', 'Barrage', 'Force Cannon'],
        'Juggernaut': ['Drain', 'Fireball', 'Force Cannon'],
        'Diver': ['Fireball', 'Cripple', 'Force Cannon'],
        'Burst Mage': ['Fireball', 'Barrage', 'Force Cannon'],
        'Battle Mage': ['Energize', 'Barrage', 'Force Cannon'],
        'Artillery Mage': ['Fireball', 'Barrage', 'Force Cannon'],
        'Control Mage': ['Stomp', 'Barrage', 'Force Cannon'],
        'Assassin': ['Barrage', 'Pin Down', 'Force Cannon'],
        'Skirmisher': ['Energize', 'Barrage', 'Force Cannon'],
        'Marksman': ['Barrage', 'Fireball', 'Force Cannon']
    },
    'Control Mage': {
        'None': ['', '', ''],
        'Utility': ['Stomp', 'Force Wall', 'Singularity'],
        'Healer': ['Stonp', 'Restore', 'Singularity'],
        'Vanguard': ['Pin Down', 'Force Wall', 'Singularity'],
        'Warden': ['Force Wall', 'Stomp', 'Singularity'],
        'Juggernaut': ['Energize', 'Stomp', 'Singularity'],
        'Diver': ['Close In', 'Fireball', 'Singularity'],
        'Burst Mage': ['Fireball', 'Force Wall', 'Singularity'],
        'Battle Mage': ['Force Wall', 'Energize', 'Singularity'],
        'Artillery Mage': ['Barrage', 'Force Wall', 'Singularity'],
        'Control Mage': ['Energize', 'Force Wall', 'Singularity'],
        'Assassin': ['Fireball', 'Energize', 'Singularity'],
        'Skirmisher': ['Energize', 'Stomp', 'Singularity'],
        'Marksman': ['Barrage', 'Stomp', 'Singularity']
    },
    'Assassin': {
        'None': ['', '', ''],
        'Utility': ['Stone Boots', 'Chop', 'Eliminate'],
        'Healer': ['Enrage', 'Close In', 'Eliminate'],
        'Vanguard': ['Stone Boots', 'Chop', 'Eliminate'],
        'Warden': ['Close In', 'Stomp', 'Eliminate'],
        'Juggernaut': ['Enrage', 'Close In', 'Eliminate'],
        'Diver': ['Stone Boots', 'Pierce', 'Eliminate'],
        'Burst Mage': ['Close In', 'Fireball', 'Eliminate'],
        'Battle Mage': ['Energize', 'Pierce', 'Eliminate'],
        'Artillery Mage': ['Pierce', 'Barrage', 'Eliminate'],
        'Control Mage': ['Hook', 'Pierce', 'Eliminate'],
        'Assassin': ['Pierce', 'Close In', 'Eliminate'],
        'Skirmisher': ['Pierce', 'Chop', 'Eliminate'],
        'Marksman': ['Pierce', 'Twin Arrows', 'Eliminate']
    },
    'Skirmisher': {
        'None': ['', '', ''],
        'Utility': ['Engrage', 'Chop', 'Lightning Strike'],
        'Healer': ['Boost', 'Chop', 'Lightning Strike'],
        'Vanguard': ['Pin Down', 'Chop', 'Lightning Strike'],
        'Warden': ['Pin Down', 'Boost', 'Lightning Strike'],
        'Juggernaut': ['Pin Down', 'Chop', 'Lightning Strike'],
        'Diver': ['Close In', 'Chop', 'Lightning Strike'],
        'Burst Mage': ['Pierce', 'Fireball', 'Lightning Strike'],
        'Battle Mage': ['Pierce', 'Energize', 'Lightning Strike'],
        'Artillery Mage': ['Pierce', 'Fireball', 'Lightning Strike'],
        'Control Mage': ['Energize', 'Close In', 'Lightning Strike'],
        'Assassin': ['Pierce', 'Close In', 'Lightning Strike'],
        'Skirmisher': ['Boost', 'Pierce', 'Lightning Strike'],
        'Marksman': ['Pierce', 'Twin Arrows', 'Lightning Strike']
    },
    'Marksman': {
        'None': ['', '', ''],
        'Utility': ['Boost', 'Volley', 'Spray and Prey'],
        'Healer': ['Boost', 'Twin Arrows', 'Spray and Prey'],
        'Vanguard': ['Stone Boots', 'Volley', 'Spray and Prey'],
        'Warden': ['Stomp', 'Volley', 'Spray and Prey'],
        'Juggernaut': ['Twin Arrows', 'Chop', 'Spray and Prey'],
        'Diver': ['Stone Boots', 'Twin Arrows', 'Spray and Prey'],
        'Burst Mage': ['Fireball', 'Twin Arrows', 'Spray and Prey'],
        'Battle Mage': ['Energize', 'Volley', 'Spray and Prey'],
        'Artillery Mage': ['Barrage', 'Twin Arrows', 'Spray and Prey'],
        'Control Mage': ['Stomp', 'Volley', 'Spray and Prey'],
        'Assassin': ['Twin Arrows', 'Pierce', 'Spray and Prey'],
        'Skirmisher': ['Volley', 'Chop', 'Spray and Prey'],
        'Marksman': ['Twin Arrows', 'Volley', 'Spray and Prey']
    },
}

SKILL_LIST = {
    'Loaf Around': {'cost': 0, 'desc': "Stands around doing nothing, damaging their own work ethic."},
    'Rest': {'cost': 0, 'desc': "Takes a nap, recovering 1 health per turn."},
    'Splash': {'cost': 1, 'desc': "Uses all of their energy to flop around! ...accomplishing nothing."},

    'Barrier': {'cost': 2, 'desc': "Shields self or ally for 2 health for 1 turn, blocking incoming damage."},
    'Restore': {'cost': 2, 'desc': "Restores 2 health to self or ally."},
    'Concussion': {'cost': 3, 'desc': 'Forcefully strike an enemy, dealing 1 damage with a 66% chance to stun.'},
    'Cripple': {'cost': 2, 'desc': "Attack the target's feet, dealing 1 damage and slowing them for 1 turn."},
    'Rally': {'cost': 1, 'desc': "Issue a battle cry increasing 2 allies' attack by 1 for this turn."},
    'Boost': {'cost': 1, 'desc': "Imbue an ally with power, increasing their speed and attack by 1 for this turn."},
    'Drain': {'cost': 2, 'desc': "Drain an enemy, stealing 1 health from them."},
    'Stone Boots': {'cost': 2, 'desc': "Raise stone from the ground, trapping an enemy's feet for this turn."},
    'Bulk Up': {'cost': 1, 'desc': "Raise defense of self or ally by 1 for this turn."},
    'Enrage': {'cost': 1, 'desc': "Get self or ally's blood pumping to increase their attack and defense by 1 for this "
                                  "turn."},
    'Close In': {'cost': 2, 'desc': "Move with speed and power, closing the distance on an enemy and striking them for"
                                    " 1 damage."},
    'Hook': {'cost': 3, 'desc': "Throws out their arms a decieving distance, pulling an enemy back to them."},
    'Reinforce': {'cost': 2, 'desc': "Pulls up a shield, blocking all ranged attacks passing by."},
    'Pierce': {'cost': 2, 'desc': "Pierce all enemies in front, dealing 2 damage to the first one hit, and 1 to the "
                                  "rest."},
    'Chop': {'cost': 2, 'desc': "Forces down on an enemy with staggering force, dealing 2 damage."},
    'Stomp': {'cost': 2, 'desc': "Stomp with a furious force, pushing all nearby enemies back."},
    'Pin Down': {'cost': 3, 'desc': "Leap on top of a nearby foe, snaring them into the ground for this turn."},
    'Energize': {'cost': 2, 'desc': "Fills the area with magical energy, detonating it to deal 1 damage to all nearby "
                                    "foes."},
    'Fireball': {'cost': 2, 'desc': "Launches a fireball at an enemy, dealing 2 damage."},
    'Barrage': {'cost': 3, 'desc': "Fires magical bolts from long range, dealing 2 damage to an enemy"},
    'Force Wall': {'cost': 3, 'desc': "Creates a wall of magic forcing any enemies back that try to cross it. Lasts 1"
                                      " turn."},
    'Twin Arrows': {'cost': 2, 'desc': "Fires two arrows at an enemy, dealing two damage."},
    'Volley': {'cost': 2, 'desc': "Fire three arrows in a volley, dealing 1 damage (max) to enemies in front."},


    'Driving Force': {'cost': 5, 'desc': "Increases all allies' speed by 2 and gives them a 1 turn shield for"
                                         " 1 health."},
    'Saving Grace': {'cost': 5, 'desc': "Heals all members of their team for 2 health."},
    'Ionic Explosion': {'cost': 5, 'desc': "Launches an ion bomb, stunning all enemies near the blast range for one"
                                           " turn."},
    'Look At Me': {'cost': 5, 'desc': "Taunts all nearby enemies, forcing those hit to attack them and taking reduced"
                                      " damage from taunted foes."},
    'Power Within': {'cost': 5, 'desc': "Releases their inner strength, gaining 2 defense, 2 attack, and losing 1 speed"
                                        " for 2 turns."},
    'Subdue': {'cost': 5, 'desc': "Moves quickly to a nearby enemy, subduing them for 1 turn and dealing 2 damage."},
    'Magiblast': {'cost': 5, 'desc': "Pulls from dormant mana reserves, forming a lethal ball of pure magical energy."
                                     " Deals 4 damage to a single enemy."},
    'Storm Surge': {'cost': 5, 'desc': "Call lightning from the heavens, dealing 2 damage to all nearby enemies,"
                                       " healing for half of the number hit."},
    'Force Cannon': {'cost': 5, 'desc': "Fires a massive range force missile, dealing 3 damage to any single enemy"},
    'Singularity': {'cost': 5, 'desc': "Creates a singulartiy at a position, pulling all enemies into the center of it,"
                                       " dealing 1 damage to all."},
    'Eliminate': {'cost': 5, 'desc': "Slice a weakened enemy with a lethal blow, dealing 8 damage to an enemy with 4"
                                     " or less health"},
    'Lightning Strike': {'cost': 5, 'desc': "Slice through 2 nearby foes, moving through them and dealing 3 damage to"
                                            " each one."},
    'Spray and Prey': {'cost': 5, 'desc': "Release 5 arrows, dealing 5 damage split among nearby enemies."}
}
